server {
    listen 80;
    listen [::]:80;
    server_name api.demo.stovash.com;

    client_max_body_size 25m;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
        default_type text/plain;
    }

    location / {
        proxy_pass http://127.0.0.1:5061;
        include /etc/nginx/snippets/stovash-proxy.conf;
    }
}
