export const DEFAULT_LEDGER_ACCOUNTS: Array<{ code: string; name: string; type: 'ASSET' | 'LIABILITY' | 'EQUITY' | 'REVENUE' | 'EXPENSE' }> = [
  { code: '1001', name: 'Cash on Hand', type: 'ASSET' },
  { code: '1002', name: 'Mobile Money', type: 'ASSET' },
  { code: '1003', name: 'Bank', type: 'ASSET' },
  { code: '1004', name: 'Card', type: 'ASSET' },
  { code: '1101', name: 'Accounts Receivable', type: 'ASSET' },
  { code: '1200', name: 'Loans Receivable', type: 'ASSET' },
  { code: '1300', name: 'Inventory', type: 'ASSET' },
  { code: '2001', name: 'Accounts Payable', type: 'LIABILITY' },
  { code: '2100', name: 'Accounts Payable', type: 'LIABILITY' },
  { code: '2200', name: 'Business Loans Payable', type: 'LIABILITY' },
  { code: '3000', name: 'Owner Equity', type: 'EQUITY' },
  { code: '4000', name: 'Sales Revenue', type: 'REVENUE' },
  { code: '5000', name: 'Cost of Goods Sold', type: 'EXPENSE' },
  { code: '6100', name: 'Inventory Loss', type: 'EXPENSE' },
  { code: '6200', name: 'Rent', type: 'EXPENSE' },
  { code: '6210', name: 'Isuku (Cleaning)', type: 'EXPENSE' },
  { code: '6220', name: 'Electricity', type: 'EXPENSE' },
  { code: '6230', name: 'Internet', type: 'EXPENSE' },
  { code: '6240', name: 'Salaries', type: 'EXPENSE' },
  { code: '6250', name: 'Taxes', type: 'EXPENSE' },
  { code: '6260', name: 'Field expenses', type: 'EXPENSE' },
];
